// Code generated by MockGen. DO NOT EDIT.
// Source: agent_memory.go
//
// Generated by this command:
//
//	mockgen -source agent_memory.go -destination mock_agent_memory_repo/mock_agent.go
//

// Package mock_agent_memory_repo is a generated GoMock package.
package mock_agent_memory_repo

import (
	agent_memory_entity "agentre/internal/model/entity/agent_memory_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAgentMemoryRepo is a mock of AgentMemoryRepo interface.
type MockAgentMemoryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAgentMemoryRepoMockRecorder
	isgomock struct{}
}

// MockAgentMemoryRepoMockRecorder is the mock recorder for MockAgentMemoryRepo.
type MockAgentMemoryRepoMockRecorder struct {
	mock *MockAgentMemoryRepo
}

// NewMockAgentMemoryRepo creates a new mock instance.
func NewMockAgentMemoryRepo(ctrl *gomock.Controller) *MockAgentMemoryRepo {
	mock := &MockAgentMemoryRepo{ctrl: ctrl}
	mock.recorder = &MockAgentMemoryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentMemoryRepo) EXPECT() *MockAgentMemoryRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockAgentMemoryRepo) Create(ctx context.Context, m *agent_memory_entity.AgentMemory) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAgentMemoryRepoMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAgentMemoryRepo)(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m *MockAgentMemoryRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAgentMemoryRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAgentMemoryRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockAgentMemoryRepo) Find(ctx context.Context, id int64) (*agent_memory_entity.AgentMemory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*agent_memory_entity.AgentMemory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAgentMemoryRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAgentMemoryRepo)(nil).Find), ctx, id)
}

// FindByAgentAndKey mocks base method.
func (m *MockAgentMemoryRepo) FindByAgentAndKey(ctx context.Context, agentID int64, scope, key string) (*agent_memory_entity.AgentMemory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAgentAndKey", ctx, agentID, scope, key)
	ret0, _ := ret[0].(*agent_memory_entity.AgentMemory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAgentAndKey indicates an expected call of FindByAgentAndKey.
func (mr *MockAgentMemoryRepoMockRecorder) FindByAgentAndKey(ctx, agentID, scope, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAgentAndKey", reflect.TypeOf((*MockAgentMemoryRepo)(nil).FindByAgentAndKey), ctx, agentID, scope, key)
}

// FindBySession mocks base method.
func (m *MockAgentMemoryRepo) FindBySession(ctx context.Context, sessionID int64) ([]*agent_memory_entity.AgentMemory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySession", ctx, sessionID)
	ret0, _ := ret[0].([]*agent_memory_entity.AgentMemory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySession indicates an expected call of FindBySession.
func (mr *MockAgentMemoryRepoMockRecorder) FindBySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySession", reflect.TypeOf((*MockAgentMemoryRepo)(nil).FindBySession), ctx, sessionID)
}

// ListByAgent mocks base method.
func (m *MockAgentMemoryRepo) ListByAgent(ctx context.Context, agentID int64) ([]*agent_memory_entity.AgentMemory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAgent", ctx, agentID)
	ret0, _ := ret[0].([]*agent_memory_entity.AgentMemory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAgent indicates an expected call of ListByAgent.
func (mr *MockAgentMemoryRepoMockRecorder) ListByAgent(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAgent", reflect.TypeOf((*MockAgentMemoryRepo)(nil).ListByAgent), ctx, agentID)
}

// ListByAgentAndScope mocks base method.
func (m *MockAgentMemoryRepo) ListByAgentAndScope(ctx context.Context, agentID int64, scope string) ([]*agent_memory_entity.AgentMemory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAgentAndScope", ctx, agentID, scope)
	ret0, _ := ret[0].([]*agent_memory_entity.AgentMemory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAgentAndScope indicates an expected call of ListByAgentAndScope.
func (mr *MockAgentMemoryRepoMockRecorder) ListByAgentAndScope(ctx, agentID, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAgentAndScope", reflect.TypeOf((*MockAgentMemoryRepo)(nil).ListByAgentAndScope), ctx, agentID, scope)
}

// Update mocks base method.
func (m_2 *MockAgentMemoryRepo) Update(ctx context.Context, m *agent_memory_entity.AgentMemory) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAgentMemoryRepoMockRecorder) Update(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAgentMemoryRepo)(nil).Update), ctx, m)
}

// UpsertByAgentAndKey mocks base method.
func (m_2 *MockAgentMemoryRepo) UpsertByAgentAndKey(ctx context.Context, m *agent_memory_entity.AgentMemory) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpsertByAgentAndKey", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertByAgentAndKey indicates an expected call of UpsertByAgentAndKey.
func (mr *MockAgentMemoryRepoMockRecorder) UpsertByAgentAndKey(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertByAgentAndKey", reflect.TypeOf((*MockAgentMemoryRepo)(nil).UpsertByAgentAndKey), ctx, m)
}
