// Code generated by MockGen. DO NOT EDIT.
// Source: agent_tool.go
//
// Generated by this command:
//
//	mockgen -source agent_tool.go -destination mock_agent_tool_repo/mock_agent.go
//

// Package mock_agent_tool_repo is a generated GoMock package.
package mock_agent_tool_repo

import (
	agent_tool_entity "agentre/internal/model/entity/agent_tool_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAgentToolRepo is a mock of AgentToolRepo interface.
type MockAgentToolRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAgentToolRepoMockRecorder
	isgomock struct{}
}

// MockAgentToolRepoMockRecorder is the mock recorder for MockAgentToolRepo.
type MockAgentToolRepoMockRecorder struct {
	mock *MockAgentToolRepo
}

// NewMockAgentToolRepo creates a new mock instance.
func NewMockAgentToolRepo(ctrl *gomock.Controller) *MockAgentToolRepo {
	mock := &MockAgentToolRepo{ctrl: ctrl}
	mock.recorder = &MockAgentToolRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentToolRepo) EXPECT() *MockAgentToolRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAgentToolRepo) Create(ctx context.Context, t *agent_tool_entity.AgentTool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAgentToolRepoMockRecorder) Create(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAgentToolRepo)(nil).Create), ctx, t)
}

// Delete mocks base method.
func (m *MockAgentToolRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAgentToolRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAgentToolRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockAgentToolRepo) Find(ctx context.Context, id int64) (*agent_tool_entity.AgentTool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*agent_tool_entity.AgentTool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAgentToolRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAgentToolRepo)(nil).Find), ctx, id)
}

// FindByName mocks base method.
func (m *MockAgentToolRepo) FindByName(ctx context.Context, agentID int64, name string) (*agent_tool_entity.AgentTool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, agentID, name)
	ret0, _ := ret[0].(*agent_tool_entity.AgentTool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockAgentToolRepoMockRecorder) FindByName(ctx, agentID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockAgentToolRepo)(nil).FindByName), ctx, agentID, name)
}

// ListByAgent mocks base method.
func (m *MockAgentToolRepo) ListByAgent(ctx context.Context, agentID int64) ([]*agent_tool_entity.AgentTool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAgent", ctx, agentID)
	ret0, _ := ret[0].([]*agent_tool_entity.AgentTool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAgent indicates an expected call of ListByAgent.
func (mr *MockAgentToolRepoMockRecorder) ListByAgent(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAgent", reflect.TypeOf((*MockAgentToolRepo)(nil).ListByAgent), ctx, agentID)
}

// ListEnabledByAgent mocks base method.
func (m *MockAgentToolRepo) ListEnabledByAgent(ctx context.Context, agentID int64) ([]*agent_tool_entity.AgentTool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabledByAgent", ctx, agentID)
	ret0, _ := ret[0].([]*agent_tool_entity.AgentTool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnabledByAgent indicates an expected call of ListEnabledByAgent.
func (mr *MockAgentToolRepoMockRecorder) ListEnabledByAgent(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabledByAgent", reflect.TypeOf((*MockAgentToolRepo)(nil).ListEnabledByAgent), ctx, agentID)
}

// ListEnabledGlobal mocks base method.
func (m *MockAgentToolRepo) ListEnabledGlobal(ctx context.Context) ([]*agent_tool_entity.AgentTool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabledGlobal", ctx)
	ret0, _ := ret[0].([]*agent_tool_entity.AgentTool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnabledGlobal indicates an expected call of ListEnabledGlobal.
func (mr *MockAgentToolRepoMockRecorder) ListEnabledGlobal(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabledGlobal", reflect.TypeOf((*MockAgentToolRepo)(nil).ListEnabledGlobal), ctx)
}

// ListGlobal mocks base method.
func (m *MockAgentToolRepo) ListGlobal(ctx context.Context) ([]*agent_tool_entity.AgentTool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGlobal", ctx)
	ret0, _ := ret[0].([]*agent_tool_entity.AgentTool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGlobal indicates an expected call of ListGlobal.
func (mr *MockAgentToolRepoMockRecorder) ListGlobal(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGlobal", reflect.TypeOf((*MockAgentToolRepo)(nil).ListGlobal), ctx)
}

// Update mocks base method.
func (m *MockAgentToolRepo) Update(ctx context.Context, t *agent_tool_entity.AgentTool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAgentToolRepoMockRecorder) Update(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAgentToolRepo)(nil).Update), ctx, t)
}
